### PR TITLE
Update LICENSE

### PR DESCRIPTION
**Pull request by ghost**
The Node.js wrapper (Makefile, http.h, etc) used in Mitol is obviously copy-pasted from µWebSockets.

### CODE REVIEW

**Comment by ghost** [comment]
@Helidium What address should I specify in my DMCA?

https://help.github.com/articles/dmca-takedown-policy/

**Comment by ghost** [comment]
> DMCA takedown notices are used by copyright owners to ask GitHub to take down infringing content. If you are a software designer or developer, you create copyrighted content every day. If someone else is using your copyrighted content in an unauthorized manner on GitHub you can send us a DMCA takedown notice to request that the infringing content be changed or removed.

**Comment by Helidium** [comment]
@alexhultman I have checked your project and made similar structure regarding the nodejs wrapper, also I have borrowed your Makefile as it is nicely made. The Makefile is obsolete and will be removed. Your project is mentioned in the README file but I didnt make any notices regarding this two files. Also http.h is somewhat similar to your solution, although quite different in terms of structure and methods used. If you insist your software has been copied I will modify the http.h and remove the Makefile, if that is what you're requesting.

**Comment by Helidium** [comment]
Pardon me @alexhultman I overlooked your commit. I made a change to LICENSE file, will this suffice?

**Comment by ghost** [comment]
> http.h is somewhat similar to your solution

No, it is not. It is completely identical down to the very last peculiar detail of my own research. If you for real believe that you just randomly created *this identical solution* out of coincidence then you are completely out of your mind. You even have the same variable names at the very same order as my work, only you changed them up somewhat.

Do you know the chances for this? This design is extremely peculiar and goes against everything you can read on doing Node.js addons. But yet here you are doing this very identical solution as I did after months of benchmarking.

This file might look simple and straightforward to you but I can tell you it took me *months* of research with multiple completely separate branches of solutions wildly separate to come up to this solution.

And of course you have these empty pipe, socket and resume functions so that it works in Express, which took me at least days to figure out from studying this horrible piece of garbage known as Express.

You make use of these reqTemplate and resTemplate objects and do shallow clones of them. Hmmmmm, what a major coincidence this was the *best* solution I tested out of 3-5 ones. And your entire addon is native and not built like the other parts of (older) µWS, wow what a major coincidence that you decided to NOT copy (the old parts of) µWS in that regard but instead perform this very peculiar stunt of trying something that you cannot find anywhere else, except for in (the newer parts of) µWS.

Nobody writes Node.js addon in the same style as I do. *Everyone* out there is making use of node-gyp, NaN and other garbage like prebuild etc. **But yet somehow you managed to make every single peculiar and absurd deviations I have made**.

This whole project is a complete rip-off with pretty much everything taken straight from µWS and then simply replaced some variable names, moved things around and then replaced the native server with a slower one. Congratulations you have earned biggest dick award :medal_military: 

And it also is very peculiar that you just happened to pick Zlib as license when 99.999999% of all code on GitHub is MIT. But I selected Zlib so of course you also copied that. What a fucking coincidence.

This project is a *fork* of my work yet you misrepresent it as being your own original work. What a fucking joke.

From the Zlib license:

> 2. Altered source versions must be plainly marked as such, and must not be misrepresented as being the original software.

Your copyright:

> Copyright (c) 2017 Marko Biškup

and

> //
// Created by helidium on 3/28/17.
//

When we both know you simply copy-pased and replaced some names here and there.

**Comment by Helidium** [comment]
Wow Alex, your exaggerations are astounding!!!

This project is nowhere near a fork of your project. If you think this is the case, then you are greatly mistaken and take my work worthless. If you will check the server code, not the node.js wrapper, you will see that the architecture and the way I handle stuff is very different from what you have written. The only thing that were meant as inspiration in my case is the node.js wrapper (http.h; I never denied not copying parts of the code from you) and of course Makefile as you also mentioned. 

Like I mentioned, I have updated the license so your project is referenced, if that is not suitable I will change the wrapper completely, because as you mentioned it is the whole project and very precious to you for all the months of benchmarking you used to write it in a way you did!

**Comment by ghost** [comment]
> If you will check the server code, not the node.js wrapper, you will see that the architecture and the way I handle stuff is very different from what you have written.

The HTTP server itself is something a child can write. It take 1 day to write. What takes time is to try and navigate this maze of horrific Node.js performance overhead and hitting the smallest overhead possible. This my friend, this is what takes time and research. If you take one wrong step in the jungle of Node.js it will cost you 96% if all your performance. I can guarantee you I have reduced my life expectancy by at least 10 years from spending all that time with Node.js and I will never again do something like that.

**Comment by Helidium** [comment]
Regarding the license, is it suitable or not?

**Comment by Helidium** [comment]
Btw the only optimisation you used in your wrapper are the function callbacks by not using the whole spaghetti as you mentioned it in the discussion. And I agree, node.js code could be written much better. All you are writing here is a JOKE! Everything else is documented in the V8 embedders guide and regarding the variable and method names they are generalized, what a coincidence! Also the method names are based on the node.js method names! What a coincidence! Object templates, What a coincidence! I can go on and on and on...

**Comment by ghost** [comment]
I'm pleased with the license change and I'm looking forward to seeing what you can bring to the table.

**Comment by ohenepee** [comment]
@alexhultman I doubt anything is coming to the table... seems he stopped development the moment you stopped working on the HTTP server in uWS... I hope you weren't right by calling him a thief, cos I really had high hopes for Mitol. :-1:  :(

**Comment by ghost** [comment]
Well yeah, there's nothing new to copy

**Comment by girng** [comment]
> I can guarantee you I have reduced my life expectancy by at least 10 years from spending all that time with Node.js and I will never again do something like that.

one of my fav quotes :D

**Pull request closed without merging**
