### PR TITLE
Fix body parse

### PR DESCRIPTION
**Pull request by askuzminov**
The body of the message comes clipped to 1 character at the end.

### CODE REVIEW

**Review by Helidium — APPROVED** [review]
Thanks for the fixes!

Appreciate it

**Comment by brandonros** [comment]
You might want to do an NPM release for this. npm install version still has this bug.

**Comment by Helidium** [comment]
You are correct, will do today in the afternoon.

Thank you for your commit and reminder ;)

**Comment by Helidium** [comment]
New version is published to NPM.

**Pull request merged**
